# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirst():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_first(self):
    self.driver.get("http://localhost/addressbook/")
    self.driver.set_window_size(550, 691)
    self.driver.find_element(By.NAME, "user").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
    self.driver.find_element(By.ID, "header").click()
    self.driver.find_element(By.LINK_TEXT, "add new").click()
    self.driver.find_element(By.NAME, "firstname").click()
    self.driver.find_element(By.NAME, "firstname").send_keys("AA")
    self.driver.find_element(By.NAME, "middlename").click()
    self.driver.find_element(By.NAME, "middlename").send_keys("s")
    self.driver.find_element(By.NAME, "lastname").click()
    self.driver.find_element(By.NAME, "lastname").send_keys("FF")
    dropdown = self.driver.find_element(By.NAME, "bday")
    dropdown.find_element(By.XPATH, "//option[. = '10']").click()
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(61) > option:nth-child(12)").click()
    self.driver.find_element(By.NAME, "bmonth").click()
    dropdown = self.driver.find_element(By.NAME, "bmonth")
    dropdown.find_element(By.XPATH, "//option[. = 'February']").click()
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(62) > option:nth-child(3)").click()
    self.driver.find_element(By.NAME, "byear").click()
    self.driver.find_element(By.NAME, "byear").send_keys("2015")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(87)").click()
  
